"use client";
import Image from "next/image";
import Link from "next/link";
import { Minus, Plus, Trash2 } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { useCart } from "@/components/cart-provider";
import { formatNaira } from "@/lib/utils";
export default function CartPage() { const { items, total, update, remove } = useCart(); return <><SiteHeader/><main className="page-shell min-h-[60vh] py-12"><p className="eyebrow">Your bag</p><h1 className="display mt-2 text-5xl">Ready when you are.</h1>{items.length === 0 ? <div className="mt-10 rounded-2xl bg-chalk p-10"><p className="text-xl font-semibold">Nothing in the bag yet.</p><p className="mt-2 text-sm">Your next match deserves better than last season's grip.</p><Link href="/shop" className="mt-6 inline-block rounded-full bg-lime px-5 py-3 text-sm font-bold">KEEP SHOPPING</Link></div> : <div className="mt-10 grid gap-10 lg:grid-cols-[1fr_360px]"><div className="divide-y">{items.map((item) => <div key={item.id} className="flex gap-4 py-5"><div className="relative h-28 w-24 shrink-0 overflow-hidden rounded-xl bg-chalk"><Image src={item.image} alt="" fill className="object-cover"/></div><div className="flex flex-1 flex-col"><div className="flex justify-between gap-4"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs uppercase text-cobalt">{item.sport}</p></div><button onClick={() => remove(item.id)} aria-label="Remove item"><Trash2 size={17}/></button></div><div className="mt-auto flex items-center justify-between"><div className="flex items-center rounded-full border"><button className="p-2" onClick={() => update(item.id, item.quantity - 1)}><Minus size={14}/></button><span className="w-7 text-center text-sm">{item.quantity}</span><button className="p-2" onClick={() => update(item.id, item.quantity + 1)}><Plus size={14}/></button></div><span className="font-mono text-sm">{formatNaira(item.price * item.quantity)}</span></div></div></div>)}</div><aside className="h-fit rounded-2xl bg-chalk p-6"><h2 className="font-semibold">Order summary</h2><div className="mt-5 flex justify-between text-sm"><span>Subtotal</span><span className="font-mono">{formatNaira(total)}</span></div><div className="mt-3 flex justify-between border-b pb-5 text-sm"><span>Delivery</span><span>At checkout</span></div><div className="mt-5 flex justify-between font-semibold"><span>Total</span><span className="font-mono">{formatNaira(total)}</span></div><Link href="/checkout" className="mt-6 block rounded-full bg-lime px-5 py-4 text-center text-sm font-bold">CHECKOUT</Link></aside></div>}</main><SiteFooter/></>; }
